export const DataAwards = [
    {
        id:1,
        href:'/',
        src:'https://riseapps.co/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2022/09/badge.png.webp'
    },
    {
        id:2,
        href:'/',
        src:'https://riseapps.co/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2022/09/badge.png.webp'
    },
    {
        id:3,
        href:'/',
        src:'https://riseapps.co/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2022/09/badge.png.webp'
    },
    {
        id:4,
        href:'/',
        src:'https://riseapps.co/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2022/09/badge.png.webp'
    },
    {
        id:5,
        href:'/',
        src:'https://riseapps.co/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2022/09/badge.png.webp'
    },
    {
        id:6,
        href:'/',
        src:'https://riseapps.co/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2022/09/badge.png.webp'
    },
    {
        id:7,
        href:'/',
        src:'https://riseapps.co/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2022/09/badge.png.webp'
    },
    {
        id:8,
        href:'/',
        src:'https://riseapps.co/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2022/09/badge.png.webp'
    },
    {
        id:9,
        href:'/',
        src:'https://riseapps.co/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2022/09/badge.png.webp'
    },
    {
        id:10,
        href:'/',
        src:'https://riseapps.co/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2022/09/badge.png.webp'
    },
]