export const DataAwards = [
    {
        id:1,
        href:'/',
        src:'https://riseapps.co/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2022/09/badge.png.webp'
    },
    {
        id:2,
        href:'/',
        src:'https://riseapps.co/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2021/01/mad_reports_5ff72f914bd421610035089.png.webp'
    },
    {
        id:3,
        href:'/',
        src:'https://riseapps.co/wp-content/uploads/2019/10/upwork.svg'
    },
    {
        id:4,
        href:'/',
        src:'https://riseapps.co/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2020/07/B2B_Companies_2020-947x1024.png.webp'
    },
    {
        id:5,
        href:'/',
        src:'https://riseapps.co/wp-content/uploads/2019/10/goodfirms.svg'
    },
    {
        id:6,
        href:'/',
        src:'https://riseapps.co/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2019/11/App_Developers_2019.png.webp'
    },
    {
        id:7,
        href:'/',
        src:'https://riseapps.co/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2019/11/Mobile-App-Development-Companies.png.webp'
    },
    {
        id:8,
        href:'/',
        src:'https://riseapps.co/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2019/11/Techreviewer_mobile_app_developers-782x1024.png.webp'
    },
    {
        id:9,
        href:'/',
        src:'https://riseapps.co/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2022/09/badge.png.webp'
    },
    {
        id:10,
        href:'/',
        src:'https://riseapps.co/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2021/01/mad_reports_5ff72f914bd421610035089.png.webp'
    },
]